### ISSUE TITLE
Use `=` for assignment rather than `<-`

### ISSUE THREAD

**Issue by grantmcdermott** [hollina/ehec-intro-to-r#1]
I've come firmly around to the idea that we should use `=` for assignment in R, especially when presenting to newcomers. We should ofc mention `<-` (and `->`), since they're likely to see this in the wild. But for newbies I think the arrow assignment adds a small yet unnecessary barrier to comprehension. Are you okay with me changing these?

**Comment by hollina** [comment]
100%. You can change anything you like. I agree with this sentiment too. Old habits die hard :)


--------------------

Alex Hollingsworth

Associate Professor

O'Neill School of Public and Environmental Affairs

Indiana University

alexjhollingsworth.com

________________________________
From: Grant McDermott ***@***.***>
Sent: Monday, July 12, 2021 4:45:25 PM
To: hollina/ehec-intro-to-r ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [hollina/ehec-intro-to-r] Use `=` for assignment rather than `<-` (#1)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


I've come firmly around to the idea that we should use = for assignment in R, especially when presenting to newcomers. We should ofc mention <- (and ->), since they're likely to see this in the wild. But for newbies I think the arrow assignment adds a small yet unnecessary barrier to comprehension. Are you okay with me changing these?
